# https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  repo: https://bitnami-labs.github.io/sealed-secrets
  chart: sealed-secrets
  version: 2.8.2
  targetNamespace: kube-system
  valuesContent: |-
    createController: true
    fullnameOverride: sealed-secrets-controller
    secretName: sealed-secrets-key
    skipRecreate: true