apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: reflector
  namespace: kube-system
spec:
  repo: "https://emberstack.github.io/helm-charts"
  chart: reflector
  version: 7.0.173
  targetNamespace: kube-system