# letsencrypt *k8slocal.com certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-k8slocal-com
  namespace: kube-system
spec:
  secretName: wildcard-local-k8slocal-com
  privateKey:
    rotationPolicy: Always
  commonName: "*.local.k8slocal.com"
  dnsNames:
    - "*.local.k8slocal.com"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: wildcard-local-k8slocal-com-acme-issuer
    kind: Issuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "dev-hello,lcl-hello"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "dev-hello,lcl-hello" # Control auto-reflection namespaces