# selfsigned clusterissuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-flask
spec:
  secretName: test-flask-tls
  privateKey:
    rotationPolicy: Always
  commonName: test-flask.monkapps.local
  dnsNames:
    - test-flask.monkapps.local
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer