apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- system/sealed-secrets-helm-chart.yaml
- system/cert-manager
- system/traefik
- data
- services

sortOptions:
  order: fifo