apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-flask
  name: test-flask
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-flask
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-flask
    spec:
      containers:
      - image: test-flask:latest
        name: test-flask
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: test-flask
  namespace: test
spec:
  ports:
  - port: 5000
  selector:
    app: test-flask