apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: portainer
  namespace: kube-system
spec:
  repo: "https://portainer.github.io/k8s"
  chart: portainer
  version: 1.0.43
  targetNamespace: kube-system
  valuesContent: |-
    service.type: ClusterIP