apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: rancher/mirrored-library-traefik
      # Update the default 2.9.4 Traefik k3s versions to 2.9.10. Traefik 2.10 requires new CRD's
      tag: 2.9.10
    dashboard:
      enabled: true
    ports:
      traefik:
        expose: true
      mysql:
        port: 3306
        protocol: TCP
        expose: true
      redis:
        port: 6379
        protocol: TCP
        expose: true
      amqp:
        port: 5672
        protocol: TCP
        expose: true
      kafka:
        port: 9092
        protocol: TCP
        expose: true
      elasticsearch:
        port: 9200
        protocol: TCP
        expose: true
    logs:
      access:
        enabled: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
        allowExternalNameServices: true
        allowEmptyServices: true
      kubernetescrd:
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: true