apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    ports:
      traefik:
        expose: true
      mysql:
        port: 3306
        protocol: TCP
        expose: true
      redis:
        port: 6379
        protocol: TCP
        expose: true
      amqp:
        port: 5672
        protocol: TCP
        expose: true
      kafka:
        port: 9092
        protocol: TCP
        expose: true
    logs:
      access:
        enabled: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
      kubernetescrd:
        allowCrossNamespace: true