apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-scheme
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    port: "443"
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-middleware
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: local
  password: test 
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: kube-system
spec:
  basicAuth:
    secret: basic-auth-middleware