apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-system
  namespace: kube-system
spec:
  repo: "https://charts.jetstack.io"
  chart: cert-manager
  version: v1.11.1
  targetNamespace: kube-system